apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
spec:
  selector:
    matchLabels:
      name: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-backend
    spec:
      containers:
      - image: {{ .Values.images.backend }}
        name: backend
        resources:
          limits:
            memory: 1000Mi
          requests:
            memory: 100Mi
        env:
          - name: MONGO_HOST
            value: "{{ .Release.Name }}-mongo"
          - name: MONGO_PORT
            value: "27017"
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-mongo-secret
                key: username
                optional: false
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-mongo-secret
                key: password
                optional: false
          - name: ELASTIC_INDEX
            value: {{ .Values.oidc.backend.elasticindex }}
          - name: ELASTIC_URL
            value: http://{{ .Release.Name }}-elastic:9200
        ports:
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    name: {{ .Release.Name }}-backend
