apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-backend-data-import
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  schedule: "0 10 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - image: {{ .Values.images.backend }}
              name: backend-download-data
              env:
                - name: ELASTIC_INDEX
                  value: {{ .Values.oidc.backend.elasticindex }}
                - name: ELASTIC_URL
                  value: http://{{ .Release.Name }}-elastic:9200
                - name: S3_KEY
                  value: {{ .Values.oidc.data_import.key }}
                - name: S3_KEYID
                  value: {{ .Values.oidc.data_import.keyid }}
                - name: S3_HOST
                  value: {{ .Values.oidc.data_import.host }}
                - name: S3_BUCKET
                  value: {{ .Values.oidc.data_import.bucket }}
              command: [ "/bin/sh","-c" ]
              args: [ "s3cmd get s3://${S3_BUCKET}/final.jsonl --host=${S3_HOST} --access_key=${S3_KEYID} --secret_key=${S3_KEY} --host-bucket=${S3_BUCKET}.${S3_HOST}; python3 /project/import_elastic.py ${ELASTIC_URL} ${ELASTIC_INDEX} ./final.jsonl" ]
          restartPolicy: Never
      backoffLimit: 4
