ingress:
  dns:
  enableSSL: true
  certIssuer: letsencrypt-prod
oidc:
  frontend:
    clientid:
    authority:
    realm:
  backend:
    elasticindex:
  data_import:
    key:
    keyid:
    host:
    bucket:
images:
  backend: gitlab.zbmed.de:5050/km/project_preview/textminingvisualizer/backend:latest
  frontend: gitlab.zbmed.de:5050/km/project_preview/textminingvisualizer/frontend:latest
