apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-add-pub-status
spec:
  schedule: "30 6 * * 2" # runs on Mondays (sec day of the week)
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            project: nfdi4health
            app.kubernetes.io/instance: {{ .Release.Name }}
            app.kubernetes.io/part-of: preview
            app.kubernetes.io/component: simple-pipeline
            app.kubernetes.io/managed-by: Helm
        spec:
          containers:
          - image: {{ .Values.images.simplePipeline }}
            name: preview-simple-pipeline
            env:
              - name: S3_KEY
                valueFrom:
                  secretKeyRef:
                    name: preview-s3-key
                    key: preview-s3-key
              - name: S3_KEYID
                valueFrom:
                  secretKeyRef:
                    name: preview-s3-keyid
                    key: preview-s3-keyid
              - name: S3_HOST
                value: {{ .Values.oidc.data_import.host }}
              - name: S3_BUCKET
                value: {{ .Values.oidc.data_import.bucket }}
            command: [ "/bin/sh","-c" ]
            args:
              - |
                file=/app/final.jsonl

                echo "Downloading input file from S3"
                s3cmd get "s3://${S3_BUCKET}/final.jsonl" "$file" \
                --host="${S3_HOST}" \
                --access_key="${S3_KEYID}" \
                --secret_key="${S3_KEY}" \
                --host-bucket="%(bucket)s.${S3_HOST}"

                if [ -e "$file" ]; then
                  echo "Download successful, running script..."
                else
                  echo "Download failed: file does not exist"
                  exit 1
                fi

                echo "Checking input file..."
                if [ -e "$file" ]; then
                  echo "File exists"
                  echo "Adding publication status..."
                  python -u /app/add_publication_status.py
                  echo "Done"
                else
                  echo "File does not exist"
                  exit 1
                fi

                echo "Script finished, checking output"
                if [ -e "$file" ]; then
                  echo "File exists"
                  echo "Uploading to S3"
                  s3cmd put "$file" "s3://${S3_BUCKET}/final.jsonl" \
                  --host="${S3_HOST}" \
                  --access_key="${S3_KEYID}" \
                  --secret_key="${S3_KEY}" \
                  --host-bucket="%(bucket)s.${S3_HOST}"
                  echo "Upload done"
                else
                  echo "File does not exist"
                  exit 1
                fi
            resources:
              requests:
                memory: 4000Mi
                cpu: 8m
          restartPolicy: Never
          imagePullSecrets:
            - name: regcred
      backoffLimit: 4


